const countryCurrencies = {
    afghanistan: "؋",
    albania: "L",
    algeria: "دج",
    andorra: "€",
    angola: "Kz",
    "antigua and barbuda": "$",
    argentina: "$",
    armenia: "֏",
    australia: "$",
    austria: "€",
    azerbaijan: "₼",
    bahamas: "$",
    bahrain: ".د.ب",
    bangladesh: "৳",
    barbados: "$",
    belarus: "Br",
    belgium: "€",
    belize: "$",
    benin: "CFA",
    bhutan: "Nu.",
    bolivia: "Bs.",
    "bosnia and herzegovina": "KM",
    botswana: "P",
    brazil: "R$",
    brunei: "$",
    bulgaria: "лв",
    "burkina faso": "CFA",
    burundi: "FBu",
    "cabo verde": "$",
    cambodia: "៛",
    cameroon: "CFA",
    canada: "$",
    "central african republic": "CFA",
    chad: "CFA",
    chile: "$",
    china: "¥",
    colombia: "$",
    comoros: "CF",
    "congo (congo-brazzaville)": "CFA",
    "costa rica": "₡",
    croatia: "€",
    cuba: "$",
    cyprus: "€",
    "czechia (czech republic)": "Kč",
    "democratic republic of the congo": "CFA",
    denmark: "kr",
    djibouti: "Fdj",
    dominica: "$",
    "dominican republic": "$",
    ecuador: "$",
    egypt: "£",
    "el salvador": "$",
    "equatorial guinea": "CFA",
    eritrea: "Nfk",
    estonia: "€",
    'eswatini (fmr. "swaziland")': "E",
    ethiopia: "Br",
    fiji: "$",
    finland: "€",
    france: "€",
    gabon: "CFA",
    gambia: "D",
    georgia: "₾",
    germany: "€",
    ghana: "₵",
    greece: "€",
    grenada: "$",
    guatemala: "Q",
    guinea: "FG",
    "guinea-bissau": "CFA",
    guyana: "$",
    haiti: "G",
    "holy see": "€",
    honduras: "L",
    hungary: "Ft",
    iceland: "kr",
    india: "₹",
    indonesia: "Rp",
    iran: "﷼",
    iraq: "ع.د",
    ireland: "€",
    israel: "₪",
    italy: "€",
    jamaica: "$",
    japan: "¥",
    jordan: "د.ا",
    kazakhstan: "₸",
    kenya: "Sh",
    kiribati: "$",
    kuwait: "د.ك",
    kyrgyzstan: "с",
    laos: "₭",
    latvia: "€",
    lebanon: "ل.ل",
    lesotho: "L",
    liberia: "$",
    libya: "ل.د",
    liechtenstein: "Fr",
    lithuania: "€",
    luxembourg: "€",
    madagascar: "Ar",
    malawi: "MK",
    malaysia: "RM",
    maldives: "ރ.",
    mali: "CFA",
    malta: "€",
    "marshall islands": "$",
    mauritania: "UM",
    mauritius: "₨",
    mexico: "$",
    micronesia: "$",
    moldova: "L",
    monaco: "€",
    mongolia: "₮",
    montenegro: "€",
    morocco: "د.م.",
    mozambique: "MT",
    "myanmar (formerly burma)": "K",
    namibia: "$",
    nauru: "$",
    nepal: "₨",
    netherlands: "€",
    "new zealand": "$",
    nicaragua: "C$",
    niger: "CFA",
    nigeria: "₦",
    "north korea": "₩",
    "north macedonia": "ден",
    norway: "kr",
    oman: "﷼",
    pakistan: "₨",
    palau: "$",
    "palestine state": "₪",
    panama: "B/.",
    "papua new guinea": "K",
    paraguay: "₲",
    peru: "S/",
    philippines: "₱",
    poland: "zł",
    portugal: "€",
    qatar: "﷼",
    romania: "lei",
    russia: "₽",
    rwanda: "FRw",
    "saint kitts and nevis": "$",
    "saint lucia": "$",
    "saint vincent and the grenadines": "$",
    samoa: "T",
    "san marino": "€",
    "sao tome and principe": "Db",
    "saudi arabia": "﷼",
    senegal: "CFA",
    serbia: "дин",
    seychelles: "₨",
    "sierra leone": "Le",
    singapore: "$",
    slovakia: "€",
    slovenia: "€",
    "solomon islands": "$",
    somalia: "Sh",
    "south africa": "R",
    "south korea": "₩",
    "south sudan": "£",
    spain: "€",
    "sri lanka": "₨",
    sudan: "£",
    suriname: "$",
    sweden: "kr",
    switzerland: "CHF",
    syria: "£",
    tajikistan: "ЅМ",
    tanzania: "Sh",
    thailand: "฿",
    "timor-leste": "$",
    togo: "CFA",
    tonga: "T$",
    "trinidad and tobago": "$",
    tunisia: "د.ت",
    turkey: "₺",
    turkmenistan: "m",
    tuvalu: "$",
    uganda: "Sh",
    ukraine: "₴",
    "united arab emirates": "د.إ",
    "united kingdom": "£",
    "united states of america": "$",
    uruguay: "$",
    uzbekistan: "so'm",
    vanuatu: "Vt",
    venezuela: "Bs.",
    vietnam: "₫",
    yemen: "﷼",
    zambia: "ZK",
    zimbabwe: "$",
};

export default countryCurrencies;